### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/metatag#12]
After installation the message appears:

> Please visit the Metatag settings page to determine which types of content should allow meta tags.

The link goes to **admin/config/search/metatags/settings** but it seems it should be **admin/config/metadata/metatags/settings**.

**Comment by jenlampton** [comment]
Thanks @laryn! Found and fixed :)

**Comment by ghost** [comment]
I can confirm that this hasn't been fixed in 1.x-1.x. Laryn has provided a fix in a separate branch that can be merged though.

**Comment by jenlampton** [comment]
I found the pull request here: https://github.com/backdrop-contrib/metatag/pull/26

**Comment by jenlampton** [comment]
Closing issue now :)
