### ISSUE TITLE
[UX] Unnecessary messages when creating node types

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/metatag#15]
When creating a new node type, I see the message `Metatag support has been enabled for the X content type.`  Is this message really necessary? To me it's only telling me what I would expect, and adds clutter to the messages area. I'm thinking about removing this, leaving here for feedback.

**Comment by ghost** [comment]
Yes, please remove :-)

**Comment by jenlampton** [comment]
Removed.
