### ISSUE TITLE
Indicate when a default value is used for empty fields

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/metatag#19]
When adding default metatags (admin/config/metadata/metatags) for specific content types, they inherit the Content metatags, which in turn inherit the Global metatags.

It's therefore hard to know what happens if I leave a field blank - does it not appear at all, or does it get inherited? If so, from where?

I suggest doing something like the following:
![screenshot_2018-07-06 content portfolio item packweb](https://user-images.githubusercontent.com/2385329/42375315-d6412188-8123-11e8-873d-eddd4e402cf9.png)

Fields that inherit values from higher up the chain, and that aren't being overwritten with values in this form, should display placeholder text showing what the inherited value is and where it's coming from.

**Comment by ghost** [comment]
PR added. I couldn't work out how to displayed where the inherited value came from, so left that out for now.

EDIT: Here's a screencast showing what the PR does:

![peek 2018-08-10 22-36](https://user-images.githubusercontent.com/2385329/43977899-246c6a76-9cee-11e8-931b-dd0524aada95.gif)

**Comment by jenlampton** [comment]
I love this, thank you!
