### ISSUE TITLE
Allow enabling individual metatags site-wide

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/metatag#20]
When configuring metatags for various instances (global, node, content types, etc.), I'm having to scroll past lots of metatags I've never going to use on my site (e.g. Audio URL, Video, etc.).

Can we add a master list of all metatags to the settings area with a checkbox next to each one to enable/disable them on a site-wide basis? That'd really help with editing metatags since you're then only seeing the subset that you'll most likely want to use...

**Comment by ghost** [comment]
Made a PR that addresses this.

**Comment by ghost** [comment]
There's an issue with caching, where you have to clear caches on each form before the hidden tags will actually be hidden...

**Comment by jenlampton** [comment]
I love this idea! 
I'd like to go one step further, and set the default to having most of these tags hidden :) 

Would you be willing to update the PR to include your settings for what you've hidden?

**Comment by ghost** [comment]
@jenlampton Sure, I added a new commit to the PR that adds a default config for disabled metatags.

**Comment by jenlampton** [comment]
Looking over the PR, I had a thought... would it make more sense to specify which tags are enabled, rather than those that are disabled? Other than that thought, the PR looks great 👍

**Comment by ghost** [comment]
I've updated the PR with a single commit that adds the ability (and requirement) to enable metatags. Give that a try and let me know how it goes.

**Comment by ghost** [comment]
New PR with latest changes: https://github.com/backdrop-contrib/metatag/pull/66
