### ISSUE TITLE
Broken links in Requirements section

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/metatag#31]
The status report gives an info line from Metatag recommending Imagecache Token, but this module doesn't exist and the link is also broken. Should we just remove this (or comment it out until the module is available)?

![screen shot 2019-01-03 at 11 23 06 am](https://user-images.githubusercontent.com/871421/50651751-f80ad700-0f49-11e9-85b0-ea45fbade722.jpg)

https://github.com/backdrop-contrib/metatag/blob/ea4483b400a5095ac4f64f252e3f1ad82c27ba73/metatag.install#L42-L51

**Comment by laryn** [comment]
Note: Same goes for the line above it:

https://github.com/backdrop-contrib/metatag/blob/ea4483b400a5095ac4f64f252e3f1ad82c27ba73/metatag.install#L29-L51

The `Entity_Translation` section needs updating as it's checking for a D7 version and like the imagecache_token check above, it is linking to `backdrop.org` (instead of `backdropcms.org`) but there is no Backdrop version of the module in the first place.

**Comment by jenlampton** [comment]
I have commented out these requirements, but added @todos to put them back if/when they are needed.
