### ISSUE TITLE
Fatal error: Class 'SearchApiAbstractService' not found

### ISSUE THREAD

**Issue by VasasA** [backdrop-contrib/metatag#34]
See this: https://forum.backdropcms.org/node/551

[Posted by laz](https://forum.backdropcms.org/node/551):

> i have installed the coder_upgrade module, and placed the unpacked d7 module inside the <docroot>/files/coder_upgrade/new/  directory. the module i am trying to port is the php (php filter) module from d7 core.
> 
> when i select the module and click "convert files", i get the white screen of death. when i turn on error display, i get this:
> 
> Fatal error: Class 'SearchApiAbstractService' not found in /home3/wxvmwlmy/public_html/.domains/polygonpolitics.com/modules/metatag/tests/metatag_search_test.module on line 22
> 
> clearly something is not right. do i need to do something different (from what is described in the instructions on the module page on backdropcms.org) since it is a core module, and also actually a sub-module ?

**Comment by klonos** [comment]
Thanks for filing this issue @VasasA 👍

@jenlampton it seems that this may be caused when the search_api module is not installed/enabled (can someone please confirm this?).

The search_api module is already declared as a dependency in [`metatag_search_test.info`](https://github.com/backdrop-contrib/metatag/blob/1.x-1.x/tests/metatag_search_test.info), so this could be a Backdrop core bug if this happens with search_api not present (it is my understanding that in that case, the test should not run in the first place).

**Comment by jenlampton** [comment]
I think the real question is: why is coder upgrade module doing *anything* with metatag module, especially trying to run its tests? Sounds like a bug in coder upgrade. 

There's no core bug here unless this happened while you are using core to run tests. Not only are we not using core to perform this action, but coder shouldn't be running tests at all, I don't think. 

If coder *is* trying to run tests, it may need to be updated to work how backdrop runs tests, instead of how Drupal runs tests.

**Comment by besmeted** [comment]
> Thanks for filing this issue @VasasA 👍
> 
> @jenlampton it seems that this may be caused when the search_api module is not installed/enabled (can someone please confirm this?).
> 
> The search_api module is already declared as a dependency in [`metatag_search_test.info`](https://github.com/backdrop-contrib/metatag/blob/1.x-1.x/tests/metatag_search_test.info), so this could be a Backdrop core bug if this happens with search_api not present (it is my understanding that in that case, the test should not run in the first place).

I can confirm that installing the search api module before installing the code upgrade module everything work as it should be working

**Comment by bugfolder** [comment]
I just ran into this. It's not that coder_upgrade is running tests, but it **is** trying to `module_load_include()` all modules, including disabled modules (which still seems wrong).

So, I agree with @jenlampton that this is a bug in coder_upgrade. There's a bug filed over there. https://github.com/backdrop-contrib/coder_upgrade/issues/59

**Comment by quicksketch** [comment]
This was fixed over in https://github.com/backdrop-contrib/coder_upgrade/issues/59. Thanks @bugfolder!
