### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/metatag#40]
I was troubleshooting https://forum.backdropcms.org/forum/newbie-problem-metatag and when trying to recreate the scenario I am seeing this error in my log:

> Warning: count(): Parameter must be an array or an object that implements Countable in metatag_metatag_config_instance_info() (line 22 of /path/modules/metatag/metatag.metatag.inc).

This may be a PHP 7.2 issue.

**Comment by jenlampton** [comment]
Fixed via https://github.com/backdrop-contrib/metatag/issues/49
