### ISSUE TITLE
php warning "Parameter must be an array or an object that implements Countable"

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/metatag#49]
This is an issue I first mentioned here: https://github.com/backdrop-contrib/metatag/issues/48

This is a php warning message triggered by the metatag_metatag_config_instance_info() function, in  metatag.metatag.inc file, line 22. It is just a typo. Will fill a PR.

**Comment by indigoxela** [comment]
This Issue looks like a duplicate of https://github.com/backdrop-contrib/metatag/issues/40

Anyway, this one here has a <strike>PR</strike> branch.

I can confirm that it fixes the warning when visiting admin/config/metadata/metatags/config.
And, yes, obviously a typo. :stuck_out_tongue_winking_eye: 

@jenlampton this looks good for a merge.

**Comment by jenlampton** [comment]
Merged thank you both :)
