### ISSUE TITLE
Undefined index description in metatag feeds importer

### ISSUE THREAD

**Issue by Egarbeil** [backdrop-contrib/metatag#53]
I receive the following error when updating field mappings in the Feeds Importer (4 times): 

Notice: Undefined index: description in metatag_feeds_processor_targets_alter() (line 17 of /home/XXXXXXXX/draft/modules/metatag/metatag.feeds.inc)

**Comment by jenlampton** [comment]
Thank you for reporting this PHP notice!

**Comment by herbdool** [comment]
I noticed the error too while doing a Backdrop Live demo today

**Comment by Egarbeil** [comment]
That’s not a fun way to see it :-(


Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by jenlampton** [comment]
I noticed it there too :( sorry @herbdool

**Comment by laryn** [comment]
I added a simple PR for this one.
