### ISSUE TITLE
Fix remaining broken functional tests (and the functionality they test, if broken)

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/metatag#58]
This is a follow-up for https://github.com/backdrop-contrib/metatag/issues/56

Two tests are still failing:

- Metatag: output caching: 92 passes, 0 fails, 0 exceptions, and 24 debug messages (doesn't complete)
- Metatag tags: Favicons: 61 passes, 0 fails, 3 exceptions, and 11 debug messages.

Regarding the output caching: I suspect that the functionality is broken, too. It ends up with an AJAX HTTP error, when run via UI.

Regarding the favicons test: there's a related core issue, but I think the problem is in Metatag module. I didn't want to spend more time to fix tests that are unrelated to the other issue, so I opened a new issue for this.

**Comment by indigoxela** [comment]
Here we go, a [starting point](https://github.com/backdrop-contrib/metatag/pull/59)

The first commit fixes test "Metatag tags: Favicons".

@jenlampton That's sort of related to this [core issue](https://github.com/backdrop/backdrop-issues/issues/3981) - which has its own PR. But the way Metatag tried to get the current favicon is definitely wrong, too. The variables in use are Drupal variables, that don't exist in Backdrop.

**Comment by jenlampton** [comment]
@indigoxela thank you for all your work on metatag :) Would you like to be a co-maintainer?

**Comment by indigoxela** [comment]
Regarding the failing output caching test:

Hehe, so silly, I just forgot to add the param to var_export(). It's fixed now in the other PR.

And as the favicon fix has been merged, I'll close this issue.

> Would you like to be a co-maintainer?

I'm only using this module in a single project. So I don't feel like being maintainer is a good idea. But I'm still providing PRs, whenever I'm able to.
