### ISSUE TITLE
Submodule metatag_devel does not define a "type" in its info file

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/metatag#60]
See https://github.com/backdrop-contrib/metatag/blob/1.x-1.x/metatag_devel/metatag_devel.info

But type is required.

See documentation: https://api.backdropcms.org/modules (Scroll down to **type (Required)**)

**Comment by quicksketch** [comment]
Thanks @indigoxela, fixed in 9ce48f8.
