### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by mazzech** [backdrop-contrib/metatag#62]
Hi @jenlampton I am not really familiar with Github, and not sure if this is the appropriate way to ask... Is it possible to have a new release within the next couple of weeks? Joseph Flatt mentioned that you are the one who can do this, I asked him for bringing the module forward (we have a great outreach opportunity in January, but META support will be an issue). Let me know if I can be of any help (testing etc.)

**Comment by laryn** [comment]
@jenlampton I just installed this through the project installer on a site I'm working on and got hit with fatal error that has already been fixed and merged. I also support a new release!

> Error: Call to undefined function ctools_include() in metatag_i18n_list_metatag_config() ...

**Comment by yorkshire-pudding** [comment]
@jenlampton - A release is needed please
#74 has been fixed and merged but is still a problem.
#67 has a PR from @indigoxela that fixes it - this bug causes an issue when updating to 1.22.2
#87 has a PR from me and fixes issues when drupal_compatibility is switched off
#47 has been fixed and merged (reference by @laryn above)
#80 has been fixed and merged
#77  has been fixed and merged

**Comment by yorkshire-pudding** [comment]
#53 has a PR from @laryn

**Comment by yorkshire-pudding** [comment]
#30 has a PR from @alanmels

**Comment by quicksketch** [comment]
Thanks for summarizing @yorkshire-pudding. I'm checking with @jenlampton to get permission to pull in some of these fixes and make a new release.

**Comment by jenlampton** [comment]
I merged a handful of the open PRs, thank you everyone!!! I'll let @quicksketch have a look through anything else, and we can make a new release when ready.

**Comment by quicksketch** [comment]
A new https://github.com/backdrop-contrib/metatag/releases/tag/1.x-1.22.2 release is out now. :smile:
