### ISSUE TITLE
Undefined property: stdClass::$language 

### ISSUE THREAD

**Issue by simone960** [backdrop-contrib/metatag#70]
I have created a Views page and override the Metatag in Views, I noticed every time I view the page, there's a message in the recent log messages:

`Notice: Undefined property: stdClass::$language in metatag_views_preprocess_page() (line 127 of /var/lib/tugboat/backdrop/modules/metatag/metatag_views/metatag_views.module).`

So I fill the "Content language" with "und", the notice will still appear, but if I fill it as "en", an extra notice also shown up:

`Theme hook "metatag_http_equiv" not found.`

Here's the demo site I created:

https://latest-ur0jttnru8wwdwjjt9ghmo7q8tzgmli1.tugboat.qa

The Views page:
https://latest-ur0jttnru8wwdwjjt9ghmo7q8tzgmli1.tugboat.qa/post

**Comment by herbdool** [comment]
It likely needs to be `->langcode` to match the changes in core.

**Comment by quicksketch** [comment]
Thanks @simone960 and @herbdool. There had been some instances of `$node->language` and `$language->language` that both needed to be updated to `->langcode` like Herb said. I fixed these in https://github.com/backdrop-contrib/metatag/pull/91. Tests are increasingly passed, but there are other unrelated issues to this one that need to be fixed yet. I'm working through these and hope to have a new release out shortly.
