### ISSUE TITLE
Where to override favicon ?

### ISSUE THREAD

**Issue by simone960** [backdrop-contrib/metatag#71]
I have enabled the "Metatag: favicons", but I don't see any interface where I can override the favicon. There's nothing happening after enabling the module.  Please advise. Thanks.

**Comment by laryn** [comment]
@simone960 Look in the Metatag settings (**admin/config/metadata/metatags/settings**) under "Enable Meta tags" and you should see a big list of options that you can enable.

(Side note to @jenlampton I was going to add a page to the wiki with this info but the Wiki appears to be locked).

**Comment by jenlampton** [comment]
Huh, I didn't know a wiki could be locked?! I'll have a look.

**Comment by laryn** [comment]
I just checked on a repo that I maintain and it must be a default setting that changed at some point:

![github-wiki](https://user-images.githubusercontent.com/871421/140549228-199764f5-6a15-459f-bd3d-25c5c580f732.png)
